
def generate_text_prompts(categories):

       captions = ["[CLS].",
              "a photomicrograph showing [CLS].",
              "a photomicrograph of [CLS].",
              "an image of [CLS].",
              "an image showing [CLS].",
              "an example of [CLS].",
              "[CLS] is shown.",
              "this is [CLS].",
              "there is [CLS].",
              "a histopathological image showing [CLS].",
              "a histopathological image of [CLS].",
              "a histopathological photograph of [CLS].",
              "a histopathological photograph showing [CLS].",
              "shows [CLS].",
              "presence of [CLS].",
              "[CLS] is present.",
              "an H&E stained image of [CLS].",
              "an H&E stained image showing [CLS].",
              "an H&E image showing [CLS].",
              "an H&E image of [CLS].",
              "[CLS], H&E stain.",
              "[CLS], H&E."]

       prompts_dict = {"NC": ["non-cancerous tissue", "non-cancerous prostate tissue", "benign tissue",
                            "benign glands", "benign prostate glands", "benign prostate tissue"],
                     "G3": ["gleason grade 3", "gleason pattern 3", "prostate cancer, gleason grade 3",
                            "prostate cancer, gleason pattern 3", "prostate adenocarcinoma, well-differentiated",
                            "well-differentiated prostatic adenocarcinoma"],
                     "G4": ["gleason grade 4", "gleason pattern 4", "prostate cancer, gleason grade 4",
                            "prostate cancer, gleason pattern 4", "prostate adenocarcinoma, moderately differentiated",
                            "moderately differentiated prostatic adenocarcinoma"],
                     "G5": ["gleason grade 5", "gleason pattern 5", "prostate cancer, gleason grade 5",
                            "prostate cancer, gleason pattern 5", "prostate adenocarcinoma, poorly differentiated",
                            "poorly differentiated prostatic adenocarcinoma"],
                     "NT": ["lymph node"],
                     "T": ["lymph node containing metastatic tumor tissue"],
                     "NM": ["normal cells", "no mitosis"],
                     "M": ["mitosis", "atypical mitosis", "atypical cells"],
                     'Necrosis': ['necrosis'],
                     'Skeletal muscle': ['skeletal muscle'],
                     'Eccrine sweat glands': ['eccrine sweat glands'],
                     'Vessels': ['vessels'],
                     'Elastosis': ['elastosis'],
                     'Chondral tissue': ['chondral tissue'],
                     'Hair follicle': ['hair follicle'],
                     'Epidermis': ['epidermis'],
                     'Nerves': ['nerves'],
                     'Subcutis': ['subcutis'],
                     'Dermis': ['dermis'],
                     'Sebaceous glands': ['sebaceous glands'],
                     'Squamous-cell carcinoma': ['squamous-cell carcinoma'],
                     'Melanoma in-situ': ['melanoma in-situ'],
                     'Basal-cell carcinoma': ['basal-cell carcinoma'],
                     'Naevus': ['naevus'],
                     'Adipose': ['adipose'],
                     'Background': ['background'],
                     'Debris': ['debris'],
                     'Lymphocytes': ['lymphocytes'],
                     'Mucus': ['mucus'],
                     'Smooth muscle': ['smooth muscle'],
                     'Normal colon mucosa': ['normal colon mucosa'],
                     "Cancer-associated stroma": ["cancer-associated stroma"],
                     'Colorectal adenocarcinoma epithelium': ['colorectal adenocarcinoma epithelium'],
                     "adventitial tissue": ["adventitial tissue"],
                     "lamina propria mucosae": ["lamina propria mucosae"],
                     "lamina muscularis mucosae": ["lamina muscularis mucosae"],
                     "muscularis propia": ["muscularis propia"],
                     "regression area": ["regression area"],
                     "gastric mucosa": ["gastric mucosa"],
                     "oesophageal mucosa": ["oesophageal mucosa"],
                     "submucosal glands": ["submucosal glands"],
                     "submucosa": ["submucosa"],
                     "tumour": ["tumour"],
                     "areas of ulceration": ["areas of ulceration"],
                     "blood": ["blood tissue", "renal blood tissue"],
                     "cancer": ["renal cancer", "renal cancerous cancer", "renal tumor tissue"],
                     "normal tissue": ["non-cancerous tissue", "non-cancerous renal tissue", "benign tissue",
                                   "benign glands", "benign renal cells", "benign renal tissue"],
                     "stroma": ["stroma tissue", "stroma renal tissue", "stroma"]
                     }


       prompts = {}
       for iCategory in categories:
              prompts[iCategory] = [caption.replace("[CLS]", iDescription) for iDescription in prompts_dict[iCategory]
                                   for caption in captions]
       return prompts